In [15]:
# Nico T. Solitana
# De La Salle University Manila

import pandas as pd 
import numpy as np 
from data_cleaner import *
from gensim_vectorizer import *
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from training_testing import *

In [16]:
# Load Dataset
data = pd.read_csv('Dataset\\water_problem_nlp_en_for_Kaggle_filtered.csv')
data = data.fillna(0)
data.head()
data['merge'] = data['text'] 

X = data['text'] 
y = data[list(data.columns[1:6])].values 
download_necessary_functions()

In [17]:
# Trained own model
w2v_model = CreateW2VModel(data)
X = GetVectorValues(w2v_model.wv, data)

c:\Users\u721775\Documents\DebugFiles\nlp\Text_Classification\gensim_vectorizer.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X = np.array([np.array([model[i] for i in ls if i in words])


In [18]:
# Load Pretrained word2vec embeddings
model = LoadModel()

In [19]:
# Pre-trained only
# Convert tokens to Vectors and split for training and testing
X = GetVectorValues(model, data)

In [5]:
# Pre-trained model + Trained model
# Convert tokens to Vectors and split for training and testing
X = GetVectorValues(MergePretrainedTrainedModel(model, data).wv, data)

In [20]:
# Splitting Dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [21]:
# ONE VS REST + LOGISTIC REGRESSION
# Model Building, Cross Validation and Prediction
SetTrainTest(X_train, X_test, y_train, y_test)
TrainTestModel(lambda: OneVsRestClassifier(LogisticRegression(solver='lbfgs',max_iter=500)))

# Check Model Performance
accuracy, cf_matrix, f1_score, precision, recall = GetModelPerformance_Multilabel()
print('Accuracy: {} FScore: {} Precision: {} Recall: {}'.format(accuracy, f1_score, precision, recall))
print(cf_matrix)

[0.07692308 0.30769231 0.23076923 0.         0.25      ]
Accuracy: 0.5 FScore: 0.667 Precision: 0.625 Recall: 0.714
[[[0 3]
  [0 5]]

 [[0 3]
  [0 5]]

 [[7 0]
  [1 0]]

 [[5 0]
  [3 0]]

 [[8 0]
  [0 0]]]


In [8]:
# ONE VS REST + RANDOM FOREST
# Model Building, Cross Validation and Prediction
SetTrainTest(X_train, X_test, y_train, y_test)
TrainTestModel(lambda: OneVsRestClassifier(RandomForestClassifier(n_estimators=200, max_depth=20, n_jobs=-1)))

# Check Model Performance
accuracy, cf_matrix, f1_score, precision, recall = GetModelPerformance_Multilabel()
print('Accuracy: {} FScore: {} Precision: {} Recall: {}'.format(accuracy, f1_score, precision, recall))
print(cf_matrix)

[0.23076923 0.15384615 0.23076923 0.         0.25      ]
Accuracy: 0.5 FScore: 0.759 Precision: 0.786 Recall: 0.733
[[[0 2]
  [0 6]]

 [[2 1]
  [1 4]]

 [[7 0]
  [1 0]]

 [[6 0]
  [2 0]]

 [[7 0]
  [0 1]]]


In [7]:
# ONE VS REST + SVM
# Model Building, Cross Validation and Prediction
SetTrainTest(X_train, X_test, y_train, y_test)
TrainTestModel(lambda: OneVsRestClassifier(LinearSVC(C = 1, random_state=0)))

# Check Model Performance
accuracy, cf_matrix, f1_score, precision, recall = GetModelPerformance_Multilabel()
print('Accuracy: {} FScore: {} Precision: {} Recall: {}'.format(accuracy, f1_score, precision, recall))
print(cf_matrix)

[0.30769231 0.07692308 0.15384615 0.30769231 0.        ]
Accuracy: 0.5 FScore: 0.71 Precision: 0.688 Recall: 0.733
[[[0 2]
  [0 6]]

 [[0 3]
  [0 5]]

 [[7 0]
  [1 0]]

 [[6 0]
  [2 0]]

 [[7 0]
  [1 0]]]


In [22]:
# ONE VS REST + GRADIENT BOOST
# Model Building, Cross Validation and Prediction
SetTrainTest(X_train, X_test, y_train, y_test)
TrainTestModel(lambda: OneVsRestClassifier(GradientBoostingClassifier(learning_rate=10, 
                max_depth=2, random_state=0)))

# Check Model Performance
accuracy, cf_matrix, f1_score, precision, recall = GetModelPerformance_Multilabel()
print('Accuracy: {} FScore: {} Precision: {} Recall: {}'.format(accuracy, f1_score, precision, recall))
print(cf_matrix)

[0. 0. 0. 0. 0.]
Accuracy: 0.0 FScore: 0.529 Precision: 0.45 Recall: 0.643
[[[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[7 0]
  [1 0]]

 [[0 5]
  [0 3]]

 [[6 2]
  [0 0]]]
